SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

MIN_SCREEN_WIDTH = 960
MIN_SCREEN_HEIGHT = 540

FPS = 60

UI_MARGIN = 24
UI_FONT_SIZE = 36

LINE_WIDTH = 2

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 200
PLAYER_SPEED = 180

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_LIFETIME = 20.0
ASTEROID_BLINK_TIME = 3.0
ASTEROID_BLINK_INTERVAL = 0.15
ASTEROID_LARGE_SPEED = 20
ASTEROID_MEDIUM_SPEED = 40
ASTEROID_SMALL_SPEED = 100

SHOT_RADIUS = 2
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
